development:
  adapter: postgresql
  database: hacker_development
  user: viget
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: hacker_test
  user: viget
  host: localhost
  pool: 5
  timeout: 5000